server:
  port: 8080
spring:
  application:
    name: RuijiDelivery
  # druid数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruiji?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1287609286

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID #自增Id配置
      # 逻辑删除全局配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: "isDeleted"

sms:
  sign-name: "阿里云短信测试"
  template:
    valid-code: SMS_154950909
  access-key-id: LTAI5tJan7EWxEm1MADgVusz
  access-key-secret: z82nHW5V8ChuxD9iXJErLN6G5vSZDY